label ec_yggy_1:
    scene 356 at topleft with dis
    "I was thinking, mulling things over in my head..."
    "Trying to use the chaos in my head to write a few pages..."
    scene 357 at topleft with dis
    "But every few lines I wrote, I found myself distracted again..."
    "I kept thinking about Yggy's offer, the egregious and insulting offer he had made me..."
    "And the more I thought about it, the less egregious it seemed..."
    scene 358 at topleft with dis
    "But no, I was better than to fall for his antics."
    "Or was I?"
    scene 359 at topleft with dis
    "The telephone sat there, teasing me, daring me to uphold my morals..."
    "But then again, it was one of these old-timey telephones that make you pick it up just out of misguided nostalgia..."
    scene 360 at topleft with dis
    mc "Hey, uh...so...what are you doing tonight?"
    y "Well, I know one person who wouldn't have called unless SHE needed some doing tonight."
    mc "I hate that you are right."
    y "Well, don't bother hating yourself, that never leads anywhere."
    y "I'll be on my way in a minute, then you can hate me instead."
    mc "Ugh, okay."
    y "See you in a bit."
    scene 361 at topleft with dis
    "It was frightening how tipsy it made me, knowing that he was coming over."
    "I couldn't even tell if I actually believed his bullshit about his potion that could fix my lack of focus..."
    "Maybe I did believe him."
    "Or maybe, I just wanted an excuse."
    scene 362 at topleft with dis
    mc "Forgive me, father, for I am about to sin."
    scene 363 at topleft with dis
    mc "Hah, look at me. Such a mess, and we haven't even started."
    scene 361 at topleft with dis
    mc "Get a grip, Ellen, before he walks in and sees you in this pitiful state."
    scene 364 at topleft with dis
    y "Hey there, you look great."
    mc "Ugh, I don't feel great."
    y "Can't get anything written?"
    mc "Am I that transparent to you?"
    y "Well, I see the typewriter, and I see crumbled-up sheets of paper."
    scene 365 at topleft with dis
    mc "You are such a detective."
    y "And you being surprised by my \"detective work\" tells me all I need to know about the state you're in tonight."
    scene 366 at topleft with dis
    mc "Ugh, you are so right, I'm a mess."
    scene 367 at topleft with dis
    mc "What do you plan to do about that?"
    y "First, you drink this, and then you drink that."
    mc "Do I get a say in this?"
    y "You can say anything you want to me, as soon as you drink up."
    scene 368 at topleft with dis
    mc "Hah, I see how it is."
    mc "Well, gimme gimme, then."
    scene 369 at topleft with dis
    mc "Ugh, this tastes much worse than the other one."
    scene 370 at topleft with dis
    y "You'll get over it as soon as you realize how effective this stuff is."
    y "Now, my turn."
    scene 371 at topleft with dis
    y "Ugh, I mean yum, this tastes great."
    mc "What even is it?"
    scene 372 at topleft with dis
    y "Brag root, mostly."
    mc "Brag root? That's what they call it?"
    y "Makes you wonder what our ancestors knew about its powers, huh?"
    mc "Makes you, yes."
    y "You feeling anything yet?"
    mc "I feel acutely aware that I invited a guy to my hotel room who immediately goes about drugging me."
    y "All in the name of creativity."
    mc "You really know how to appeal to my dark fears of writer's block."
    y "It's not like you made a huge secret about where your weaknesses lie."
    mc "Ugh, I really didn't, did I?"
    scene 373 at topleft with dis
    mc "Okay, now we'll find out if you lied to me."
    y "Yes I did."
    mc "Okay, and what did you lie about?"
    y "That I like the color of your eyes better than the thought of your naked body in my hands."
    scene 374 at topleft with dis
    mc "Okay, first off: That is barely a lie, that's what we call getting the foot in the door."
    mc "Second, you never even said that to me."
    y "See, there's your focus back again, Ellen."
    mc "Ugh, stop playing games with me."
    y "May I suggest you get to writing, then?"
    mc "You can't just tell me what to do."
    y "Let me humbly suggest that you grab your notebook, and ignore me while I get to know you a little better."
    scene 375 at topleft with dis
    mc "Getting to know me, is that what we're calling it now?"
    y "We can also call it inspiring you to write, if you prefer that."
    scene 376 at topleft with dis
    mc "I'd prefer if you shut up and put your money where your mouth is."
    y "Good idea."
    image anim_ec_yggy_1_sex = Movie(channel="movie_dp", play="images/anim_ec_yggy_1_sex.webm", size = (1920,1080))
    show anim_ec_yggy_1_sex
    "There was just something inexplicably good about the slow, methodic way he was working me."
    "It was, like...not at all unexpected, his thrusts never catching me by surprise."
    "But instead, we both settled into a rhythm that allowed me to actually hold on to my pen and paper, and to write lines that where squiggly for sure, but not unreadable."
    "And sure enough, just like Yggy had promised me, it was like my brain was moving faster than my body, each line and paragraph forming in my head before I had finished writing the previous one down."
    y "Sorry about the mess."
    mc "Thank you for the mess."
    y "I see you are making progress."
    mc "This is good stuff, Yggy, I really don't mind what you're doing to me tonight."
    y "Glad to hear that."
    "With barely a moment of break, he slipped back into me, as if the once warm and now quickly cooling mess between my thighs was just a side concern on his mind."
    "For what seemed like an hour afterward, we didn't talk, and barely locked eyes whenever I was pulled out of my story for a second."
    "At first, I thought that he might take offense at that, but it seemed like the opposite was true."
    "It had been years since I had last felt so...comfortable being naked with someone."
    "And obviously, I had never come even close to a night like this, that just didn't seem to end - for either of us."
    hide ec_jay_2_sex_1
    scene 377_c1 at topleft with hpunch
    "When we finally ran out of steam, it became clear that neither of us would be getting any sleep that night."
    scene 379 at topleft with dis
    "So we just cuddled up, and started daydreaming in the middle of the night."
    mc "Are you gonna keep doing that to me?"
    y "That's the plan, yes."
    y "Are you done with your bestseller yet?"
    mc "Not quite, but getting closer."
    y "You wanna read it to me?"
    mc "Are you actually interested?"
    mc "Because I really don't mind if you just wanna have your way with me."
    y "That's cute, but I actually care."
    y "Makes me all warm and fuzzy inside to know I could make myself useful here."
    scene 379 at topleft with dis
    mc "Hah, alright then."
    mc "So, uh, this is a rough draft, keep that in mind."
    y "Not as rough as you'll feel in the morning."
    mc "Hah, you may be right about that."
    mc "So, here goes."
    scene 380 at topleft with dis
    mc "\"Her kitchen was tiny to begin with - but with us both in there, it became downright impossible to coexist without accidentally brushing against each other.\""
    mc "\"Sorry\", Jason mumbled, \"but I just waved him off.\""
    mc "\"I'm a big girl, Jason, I don't fall apart when you touch me.\""
    mc "\"I could feel that he wanted to say something, but swallowed the joke that was so obviously on both our minds.\""
    mc "How's that sound?"
    y "Surprisingly cute, are they neighbors or something?"
    mc "Yep, and he's married."
    y "Oh I see. Married to a real bitch, I assume?"
    mc "Mh-mh, she's really nice and friendly, and they are friends, too."
    y "Ouch, okay. I wondered why you were writing cutesy kitchen-bumping."
    y "So that's the kind of stuff you're thinking about while I'm wearing myself out in an effort to wear you down?"
    mc "You know, I was thinking that I wouldn't mind accidentally bumping into you sometime."
    y "That can be arranged."
    mc "You aren't so bad at what you do, Yggy."
    y "My ex wife would disagree with you there."
    mc "I didn't know you were married once."
    y "Ten years."
    mc "What happened?"
    y "Apparently, I became a failure, was spending too much time with my \"stupid books\", and was god awful at anything and everything."
    y "So, she offered me a choice, my books or her."
    mc "Hah, that's an easy choice."
    y "You are supposed to berate me for having the wrong priorities."
    mc "I don't know, I really enjoyed your priorities tonight."
    y "But now, I should really get back to my books."
    mc "Come on, don't leave me here like that."
    mc "You need to get your priorities straight."
    y "You are so demanding."
    mc "It's almost morning, anyway."
    mc "Go on, I want you gone by morning."
    mc "Have fun talking to your books, expecting them to talk back to you."
    y "You're talking back to me."
    mc "Until you're utterly sick of me."
    scene black at topleft with dis #todo
    y "See you around, Ellen."
    y "Try not to think too much about married men."
    y "Or, if you can't help yourself, then at least write it down."
    mc "Sounds like a plan."
    jump next_morning