label ec_yggy_1:
    scene black at topleft with dis #todo
    #todo he comes to visit us and we spend time drinking, fooling around, and writing
    "I was thinking, mulling things over in my head..."
    "Trying to use the chaos in my head to write a few pages..."
    "But every few lines I wrote, I found myself distracted again..."
    "I kept thinking about Yggy's offer, the egregious and insulting offer he had made me..."
    "And the more I thought about it, the less egregious it seemed..."
    scene black at topleft with dis #todo
    "But no, I was better than to fall for his antics."
    "Or was I?"
    scene black at topleft with dis #todo
    mc "Hey, uh...so...what are you doing tonight?"
    y "Well, I know one person who wouldn't have called unless SHE needed some doing tonight."
    mc "I hate that you are right."
    y "Well, don't bother hating yourself, that never leads anywhere."
    y "I'll be on my way in a minute, then you can hate me instead."
    mc "Ugh, okay."
    y "See you in a bit."
    scene black at topleft with dis #todo
    "It was frightening how tipsy it made me, knowing that he was coming over."
    "I couldn't even tell if I actually believed his bullshit about his potion that could fix my lack of focus..."
    "Maybe I did believe him."
    "Or maybe, I just wanted an excuse."
    mc "Forgive me, father, for I am about to sin."
    scene black at topleft with dis #todo
    mc "Hah, look at me. Such a mess, and we haven't even started."
    mc "Get a grip, Ellen, before he walks in and sees you in this pitiful state."
    scene black at topleft with dis #todo
    y "Hey there, you look great."
    mc "Ugh, I don't feel great."
    y "Can't get anything written?"
    mc "Am I that transparent to you?"
    y "Well, I see the typewriter, and I see crumbled-up sheets of paper."
    mc "You are such a detective."
    y "And you being surprised by my \"detective work\" tells me all I need to know about the state you're in tonight."
    mc "Ugh, you are so right, I'm a mess."
    mc "What do you plan to do about that?"
    y "First, you drink this, and then you drink that."
    mc "Do I get a say in this?"
    y "You can say anything you want to me, as soon as you drink up."
    mc "Hah, I see how it is."
    mc "Well, gimme gimme, then."
    mc "Ugh, this tastes much worse than the other one."
    y "You'll get over it as soon as you realize how effective this stuff is."
    y "Now, my turn."
    y "Ugh, I mean yum, this tastes great."
    mc "What even is it?"
    y "Brag root, mostly."
    mc "Brag root? That's what they call it?"
    y "Makes you wonder what our ancestors knew about its powers, huh?"
    mc "Makes you, yes."
    y "You feeling anything yet?"
    mc "I feel acutely aware that I invited a guy to my hotel room who immediately goes about drugging me."
    y "All in the name of creativity."
    mc "You really know how to appeal to my dark fears of writer's block."
    y "It's not like you made a huge secret about where your weaknesses lie."
    mc "Ugh, I really didn't, did I?"
    mc "Okay, now we'll find out if you lied to me."
    y "Yes I did."
    mc "Okay, and what did you lie about?"
    y "That I like the color of your eyes better than the thought of your naked body in my hands."
    mc "Okay, first off: That is barely a lie, that's what we call getting the foot in the door."
    mc "Second, you never even said that to me."
    y "See, there's your focus back again, Ellen."
    mc "Ugh, stop playing games with me."
    y "May I suggest you get to writing, then?"
    mc "You can't just tell me what to do."
    y "Let me humbly suggest that you grab your notebook, and ignore me while I get to know you a little better."
    scene black at topleft with dis #todo
    mc "Getting to know me, is that what we're calling it now?"
    y "We can also call it inspiring you to write, if you prefer that."
    mc "I'd prefer if you shut up and put your money where your mouth is."
    y "Good idea."
    scene black at topleft with dis #todo
    "There was just something inexplicably good about the slow, methodic way he was working me."
    "It was, like...not at all unexpected, his thrusts never catching me by surprise."




    jump next_morning