label nightclub_flashback_1:
    scene 182 at topleft with dis
    mc "So, I was going through this phase, okay?"
    s "What kind of phase?"
    mc "The I am so in charge of myself that I can afford to let go phase."
    s "Oh, I see."
    mc "So, I was in this club, you know, real shithole of a place, even by shithole standards."
    mc "Everything looked like a mixture of dirty old subway station, and rest stop toilet."
    mc "White tiling on all the walls, probably because it's easier to clean."
    mc "Neon lights, so your drunk mind thinks this is fun and exciting."
    mc "And the techno music, can't forget about the techno music."
    s "Wow, I can totally picture this. You should write books or something."
    mc "Hah, I know, right?"
    scene 183 at topleft with dis
    mc "Anyway, I liked this place, it was great for shocking my friends whenever they said they wanted to party, and I wasn't really in the mood."
    mc "They wouldn't shut up, so I would say okay, I know a really cool place that you haven't been to before..."
    mc "And after that, they would know better than to ask me out."
    s "Hah, now that is mean."
    s "Funny, though."
    s "And, did you dress the part, too?"
    s "Somehow, I can't see you really fitting into a place like that."
    scene 184 at topleft with dis
    mc "Slut boots and short skirt and everything."
    s "Now, that I would have liked to see."
    mc "So did the guys, at first, always stealing little glances on our way there."
    s "And you liked that?"
    mc "No, hated it, really."
    mc "Hated how they looked and didn't dare to say anything, nice or not, as if I was going to start crying if they made me a compliment or something."
    mc "You know, I was like, in that mood, where it really annoyed me that they thought their attraction to me was some kind of well-kept government secret."
    scene 136 at topleft with dis
    s "Ugh, I know, right?"
    s "I mean, hello? I'm a chick, you're a guy, we both don't hate each other - I mean, of course we have thought about the possibilities here, right?"
    mc "See, you get that, I get that - why didn't they get it?"
    mc "Anyway, it made me want to show them how in charge of myself I was, walking on clouds in places that made them paranoid."
    mc "And, I won't lie, it was always kinda cute how protective they got, swarming around us girls as if they were afraid of losing us to the darkness."
    s "You know, that does sound kida cute."
    mc "But that's normal-bad clubs, you know? The kind where you leave and think \"damn, I wonder if that guy who looked so sketch was actually trying to spike my drink\""
    mc "But that place, it was more like when, not if, and it was downright confusing if nothing crazy happened within five minutes of entering there."
    scene 185 at topleft with dis
    mc "It was, like, peeing on the dance floor, and everybody cheering kinda atmosphere."
    s "Ugh."
    mc "Exactly, but it was just...my thing, for a while. Dirty, gritty, everyone there was on SOMETHING, and they would offer you unmarked pills, and people were snorting stuff off of the toilet seats."
    s "But then again, that wasn't a problem, if everyone was peeing on the floors anyway."
    mc "Exactly."
    scene 186 at topleft with dis
    mc "And, you know, I somehow thrived in there, for some reason."
    mc "The guys I was with, not so much, and that was kind of part of the thrill."
    mc "I know it's shitty, but..."
    mc "Alone, I was almost bored in there, stuff couldn't really faze me."
    mc "But when I was there with some guys, I was suddenly hugging people who recognized me, giving them fist bumps, and taking pretty much whatever they would offer me."
    mc "Less to see what would happen to me, and more to see what it did to my friends, the boring idiots who were MAYBE brave enough to hold a door open for me, instead of thinking I might throw a hissyfit over it."
    s "Not gonna lie, that does sound pretty shitty."
    mc "Oh, it was, there is no denying that."
    mc "But, for a year or two, shit like that really fuelled me through the week."
    scene 134 at topleft with dis
    mc "It was, like, nothing at work could faze me, nothing on the way home, and those little flirts with my neighbor next door weren't really..."
    s "Cutting it."
    mc "Exactly."
    scene 132 at topleft with dis
    s "So, where does the embarrassing part start?"
    mc "Hah, I like the cut of your jib."
    mc "That would probably be when one of my friends really got paranoid, and tried to drag me out of there."
    scene 126 at topleft with dis
    s "Oh, bad choice!"
    mc "I was SO pissed with him, I even swatted his hand from my arm."
    scene 129 at topleft with dis
    s "Wait, he dared to touch you?"
    mc "That's what got me even more pissed, he would have never dared to come within an inch of me."
    mc "And there he was, literally dragging me away from the guy who had just offered me...something, I forgot what it was."
    mc "So, I told this guy that I would fuck him, but only if he made sure this other guy, my friend, got thrown out of the club."
    s "No way."
    mc "Yes way, like I said, I was really pissed."
    mc "And the cocktail mixing inside of me probably wasn't healthy, either."
    s "Sounds like it."
    scene 124 at topleft with dis
    s "So, what happened?"
    scene 136 at topleft with dis
    mc "Exactly that."
    s "That's...wow."
    s "Like, in the club?"
    scene 187 at topleft with dis
    mc "At the bar."
    mc "I had the barkeeper making me a drink while the guy was going at it."
    s "Holy shit, and nobody stopped that?"
    mc "Remember when I told you something crazy would always happen five minutes after walking in?"
    mc "Well, I was someone else's dose of crazy that night."
    return